# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Syumi编译

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 准备GO环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: 设置环境变量
        run: |
            GOOS=windows
            GOARCH=amd64
            CGO_ENABLED=1
            BINARY_NAME=gogs-$GOOS-$GOARCH
            echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
            echo "GOOS=$GOOS" >> $GITHUB_ENV
            echo "GOARCH=$GOARCH" >> $GITHUB_ENV
            echo "CGO_ENABLED=$CGO_ENABLED" >> $GITHUB_ENV
      - name: 编译方式
        run: go build -o "$BINARY_NAME" -v
      - name: 拷贝目录
        run: |
            mkdir -p ~/new/artifact
            cp -f ./"$BINARY_NAME" ~/new/artifact
      - name: 检查目录
        run: |
            ls -al
            pwd
      - name: 上传Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: ~/new/**/*
          retention-days: 1
